css:
  -
    location: 'gantry-assets://members.css'
    inline: ''
    extra: {  }
    priority: '0'
    name: members.css
  -
    location: ''
    inline: '#g-navigation .g-content {padding:0;}'
    extra: {  }
    priority: '0'
    name: 'navigation padding'
