name: donations
timestamp: 1705418621
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1537195582
positions: {  }
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  sample:
    sample-5174: 'Donations Message'
  spacer:
    spacer-4080: Spacer
    spacer-6432: Spacer
  content:
    system-content-6449: 'Page Content'
  logo:
    logo-7145: Logo
  custom:
    custom-7035: 'Custom HTML'
    custom-5133: Mission
    custom-2028: Membership
  menu:
    menu-5307: Menu
  copyright:
    copyright-6088: Copyright
  social:
    social-1694: Social
  branding:
    branding-6465: Branding
  mobile-menu:
    mobile-menu-8473: 'Mobile Menu'
inherit:
  default:
    header: header
    logo-7145: logo-9636
    custom-7035: custom-2856
  home:
    navigation: navigation
    main: main
    subfeature: subfeature
    footer: footer
    offcanvas: offcanvas
    menu-5307: menu-5555
    custom-5133: custom-6236
    custom-2028: custom-7402
    copyright-6088: copyright-2256
    social-1694: social-2985
    branding-6465: branding-1850
    mobile-menu-8473: mobile-menu-2938
