name: _error
timestamp: 1603223577
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9828: 'System Messages'
  simplecontent:
    simplecontent-7561: 'We are sorry!'
  content:
    system-content-3192: 'Page Content'
  logo:
    logo-4434: 'Logo / Image'
  menu:
    menu-4114: Menu
  widget:
    position-widget-4790: Search
  social:
    social-9506: Social
  blockcontent:
    blockcontent-3057: 'Block Content'
  copyright:
    copyright-3240: Copyright
  mobile-menu:
    mobile-menu-5545: 'Mobile Menu'
inherit:
  default:
    navigation: navigation
    slideshow: slideshow
    header: header
    above: above
    showcase: showcase
    utility: utility
    feature: feature
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    logo-4434: logo-9680
    menu-4114: menu-5875
    position-widget-4790: position-widget-6279
    social-9506: social-3695
    blockcontent-3057: blockcontent-5767
    copyright-3240: copyright-6444
    mobile-menu-5545: mobile-menu-2576
