name: news
timestamp: 1678990742
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9828: 'System Messages'
  heading:
    heading-6603: Heading
  contentarray:
    contentarray-4767: 'WordPress Posts'
    contentarray-4163: 'WordPress Posts'
  mobile-menu:
    mobile-menu-2576: 'Mobile Menu'
  logo:
    logo-7033: 'Logo / Image'
  menu:
    menu-4243: Menu
  widget:
    position-widget-3961: Search
  social:
    social-5552: Social
  copyright:
    copyright-6308: Copyright
inherit:
  default:
    navigation: navigation
    copyright: copyright
    logo-7033: logo-9680
    menu-4243: menu-5875
    position-widget-3961: position-widget-6279
    social-5552: social-3695
    copyright-6308: copyright-6444
