name: _body_only
timestamp: 1597769013
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1581187528
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-8729: 'System Messages'
  content:
    system-content-7208: 'Page Content'
inherit: {  }
