version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1545346302
layout:
  /top/:
    -
      - system-messages-9828
  /navigation/:
    -
      - 'logo-9680 10'
      - 'simplecontent-2729 80'
      - 'slidingmenu-6110 10'
  /slideshow/: {  }
  /header/: {  }
  /above/: {  }
  /feature/: {  }
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-position-9414
      -
        'mainbar 60':
          -
            - position-position-8547
          -
            - system-content-1120
      -
        'aside 20':
          -
            - position-position-8807
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /footer/:
    -
      - 'simplecontent-1274 20'
      - 'simplemenu-2324 80'
  /copyright/:
    -
      - 'copyright-6444 35'
      - 'social-7931 65'
  offcanvas:
    -
      - mobile-menu-2576
structure:
  top:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  navigation:
    type: section
    attributes:
      boxed: '3'
      class: ''
      variations: section-horizontal-paddings
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  header:
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  footer:
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  copyright:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  offcanvas:
    attributes:
      swipe: '0'
content:
  logo-9680:
    title: 'Logo / Image'
    block:
      variations: 'align-left nopaddingall'
  simplecontent-2729:
    title: 'Simple Content'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: standard
          created_date: ''
          content_title: ''
          author: ''
          leading_content: ''
          main_content: "<span><i class=\"fa fa-envelope-open-o\" aria-hidden=\"true\"></i>\ncontact@evergreenarts.edu</span><span><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\n+1-3435-2356-222</span>"
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'New item'
    block:
      class: hidden-phone
      variations: 'nopaddingtop nopaddingbottom center'
  slidingmenu-6110:
    title: 'Sliding menu'
    block:
      class: hidden-phone
      variations: 'align-right nopaddingtop nopaddingbottom'
  position-position-9414:
    title: Sidebar
    attributes:
      key: sidebar
  position-position-8547:
    title: MainBar
    attributes:
      key: mainbar
  position-position-8807:
    title: Aside
    attributes:
      key: aside
  simplecontent-1274:
    title: 'Simple Content'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: standard
          created_date: ''
          content_title: 'Evergreen University'
          author: ''
          leading_content: "Pkwy #502 3649 Evergreen<br />  \nCO 80439-9998 Evergreen"
          main_content: "+1-2345-6789-101<br />\ncontact@evergreensoa.edu"
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'Evergreen Details'
  simplemenu-2324:
    title: 'Simple Menu'
    attributes:
      menus:
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Planning & Administration'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Campus Safety'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Office of the Chancellor'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Facility Services'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Human Resources'
          title: 'Our campus'
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: Students
            -
              icon: ''
              link: '#'
              target: _blank
              title: Faculty
            -
              icon: ''
              link: '#'
              target: _blank
              title: Alumni
            -
              icon: ''
              link: '#'
              target: _blank
              title: Emplyees
            -
              icon: ''
              link: '#'
              target: _blank
              title: Community
          title: People
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'About School'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Apply for Admission'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Academics
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'University Life'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Our Research'
          title: 'On the Site'
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: Accessibility
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Financial Aid'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Food Services'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Housing
            -
              icon: ''
              link: '#'
              target: _blank
              title: Technologies
          title: 'Campus Life'
  copyright-6444:
    attributes:
      date:
        start: ''
        end: ''
      owner: 'by RocketTheme. All rights reserved.'
    block:
      variations: nomarginall
  social-7931:
    attributes:
      display: text_only
      items:
        -
          icon: ''
          text: Facebook
          link: 'https://www.facebook.com/RocketTheme'
          name: Facebook
        -
          icon: ''
          text: Twitter
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: ''
          text: Instagram
          link: '#'
          name: Instagram
        -
          icon: ''
          text: Tookapic
          link: '#'
          name: Tookapic
        -
          icon: ''
          text: YouTube
          link: '#'
          name: YouTube
    block:
      variations: 'nomarginall align-right'
  mobile-menu-2576:
    title: 'Mobile Menu'
