name: _body_only
timestamp: 1581187529
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1537195582
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-2810: 'System Messages'
  content:
    system-content-6961: 'Page Content'
inherit: {  }
