version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1537195582
layout:
  /main/:
    -
      - system-messages-2810
    -
      - system-content-6961
structure:
  main:
    attributes:
      boxed: ''
