name: breed-item
timestamp: 1678990741
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9828: 'System Messages'
  content:
    system-content-6560: 'Page Content'
  mobile-menu:
    mobile-menu-2576: 'Mobile Menu'
  logo:
    logo-5142: 'Logo / Image'
  menu:
    menu-3245: Menu
  widget:
    position-widget-1752: Search
  social:
    social-4068: Social
  copyright:
    copyright-3310: Copyright
inherit:
  default:
    navigation: navigation
    copyright: copyright
    logo-5142: logo-9680
    menu-3245: menu-5875
    position-widget-1752: position-widget-6279
    social-4068: social-3695
    copyright-3310: copyright-6444
