version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1537195582
layout:
  /header/:
    -
      - 'logo-2935 30'
      - 'spacer-1023 70'
  /main/:
    -
      - system-messages-7264
    -
      - system-content-7841
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6813 40'
      - 'spacer-1415 30'
      - 'branding-7843 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
