version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1570546450
layout:
  /top/:
    -
      - system-messages-9828
  /navigation/:
    -
      - 'logo-2704 15'
      - 'menu-2872 70'
      - 'button-6662 15'
  /slideshow/:
    -
      - 'position-position-6661 80'
      - 'social-8668 20'
  /header/: {  }
  /above/: {  }
  /feature/: {  }
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-position-9414
      -
        'mainbar 60':
          -
            - system-content-1120
      -
        'aside 20':
          -
            - position-position-8807
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /container-footer/:
    -
      -
        /footer/:
          -
            - simplemenu-2324
          -
            - newsletter-4035
        /copyright/:
          -
            - copyright-6444
          -
            - particlesjs-5901
  offcanvas:
    -
      - mobile-menu-2576
structure:
  top:
    type: section
    attributes:
      boxed: ''
      class: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings-large
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings-large'
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  footer:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings medpaddingbottom'
      variations: ''
  copyright:
    type: section
    attributes:
      boxed: ''
      class: section-horizontal-paddings
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    attributes:
      swipe: '0'
content:
  logo-2704:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://logo/logo.svg'
      link: '1'
      text: akuatik
      title: ''
      class: 'g-logo g-logo-akuatik'
  menu-2872:
    block:
      variations: 'center nopaddingleft nopaddingright'
  button-6662:
    attributes:
      label: 'Get a Quote'
  position-position-6661:
    title: Slideshow
    attributes:
      key: slideshow
    block:
      class: blobs
  social-8668:
    attributes:
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'https://www.facebook.com/RocketTheme'
          name: Facebook
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-github fa-fw'
          text: ''
          link: '#'
          name: GitHub
  position-position-9414:
    title: Sidebar
    attributes:
      key: sidebar
  position-position-8807:
    title: Aside
    attributes:
      key: aside
  simplemenu-2324:
    title: 'Simple Menu'
    attributes:
      menus:
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Product Strategy'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Product Engineering'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Architecture
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'UX / UI Design'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'App Development'
          title: Services
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: Facebook
            -
              icon: ''
              link: '#'
              target: _blank
              title: Instagram
            -
              icon: ''
              link: '#'
              target: _blank
              title: YouTube
            -
              icon: ''
              link: '#'
              target: _blank
              title: Tookapic
            -
              icon: ''
              link: '#'
              target: _blank
              title: Unsplash
          title: Join
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Our Blog'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Case Studies'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'WebDesign Guides'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Newsletter
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Favourite Tools'
          title: Resources
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: akuatik@rockettheme.com
            -
              icon: ''
              link: '#'
              target: _blank
              title: '1 (800) 123 4567'
          title: Contact
  newsletter-4035:
    attributes:
      layout: g-newsletter-aside
      inputboxtext: 'What''s your email address?'
      buttonclass: ''
  copyright-6444:
    attributes:
      date:
        start: ''
        end: ''
      owner: 'All rights reserved. Designed & Developed by <a href="" target="_blank">RocketTheme</a>.'
    block:
      variations: center
  particlesjs-5901:
    title: Particles
    attributes:
      sectiononly: enabled
  mobile-menu-2576:
    title: 'Mobile Menu'
