name: home
timestamp: 1593795379
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1584382114
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-5493: 'System Messages'
  logo:
    logo-5556: 'Logo / Image'
    logo-5413: 'Logo / Image'
  menu:
    menu-3224: Menu
  social:
    social-7745: Social
  simplecontent:
    simplecontent-5408: 'Simple Content'
  custom:
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  copyright:
    copyright-6757: Copyright
  horizontalmenu:
    horizontalmenu-6299: 'Horizontal Menu'
  totop:
    totop-6862: 'To Top'
  mobile-menu:
    mobile-menu-3877: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-5493: system-messages-7972
    logo-5556: logo-9608
    menu-3224: menu-6409
    social-7745: social-3171
    footer: footer
    logo-5413: logo-9571
    copyright-6757: copyright-1736
    horizontalmenu-6299: horizontalmenu-9034
    totop-6862: totop-8670
    offcanvas: offcanvas
    mobile-menu-3877: mobile-menu-5697
