name: _error
timestamp: 1581187529
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1537195582
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5259: Logo
  spacer:
    spacer-3800: Spacer
    spacer-4476: Spacer
  menu:
    menu-1534: Menu
  content:
    system-content-2173: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-9260: Copyright
  branding:
    branding-8688: Branding
  mobile-menu:
    mobile-menu-4349: Mobile-menu
inherit: {  }
