name: home
timestamp: 1603223577
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9828: 'System Messages'
  slideshow:
    slideshow-2031: Slideshow
  contentarray:
    contentarray-8813: 'Messages from President'
    contentarray-4628: News
  custom:
    custom-1909: 'Meet Our Members'
  team:
    team-5648: Breeds
  mobile-menu:
    mobile-menu-2576: 'Mobile Menu'
  logo:
    logo-5481: 'Logo / Image'
  menu:
    menu-4586: Menu
  widget:
    position-widget-5966: Search
  social:
    social-5175: Social
  blockcontent:
    blockcontent-6194: 'Block Content'
  copyright:
    copyright-3357: Copyright
inherit:
  default:
    navigation: navigation
    footer: footer
    copyright: copyright
    logo-5481: logo-9680
    menu-4586: menu-5875
    position-widget-5966: position-widget-6279
    social-5175: social-3695
    blockcontent-6194: blockcontent-5767
    copyright-3357: copyright-6444
