name: _error
timestamp: 1581187529
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1537195582
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9145: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-6916: Menu
  messages:
    system-messages-2577: 'System Messages'
  content:
    system-content-8934: 'Page Content'
  copyright:
    copyright-2730: Copyright
  spacer:
    spacer-8259: Spacer
  branding:
    branding-5304: Branding
  mobile-menu:
    mobile-menu-1809: Mobile-menu
inherit: {  }
