name: _offline
timestamp: 1581187529
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1537195582
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4138: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-3284: Menu
  messages:
    system-messages-9240: 'System Messages'
  content:
    system-content-1817: 'Page Content'
  copyright:
    copyright-9877: Copyright
  spacer:
    spacer-2117: Spacer
  branding:
    branding-5429: Branding
  mobile-menu:
    mobile-menu-9866: Mobile-menu
inherit: {  }
