version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1537195582
layout:
  /header/:
    -
      - 'logo-4138 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-3284
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-9240
    -
      - system-content-1817
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9877 40'
      - 'spacer-2117 30'
      - 'branding-5429 30'
  offcanvas:
    -
      - mobile-menu-9866
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
