name: new_ashby_farm
timestamp: 1603223577
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  infolist:
    infolist-2061: 'Info List'
  heading:
    heading-4091: Heading
  simplecontent:
    simplecontent-1800: 'Simple Content'
  logo:
    logo-1285: 'Logo / Image'
    logo-5274: 'Logo / Image'
  messages:
    system-messages-9742: 'System Messages'
  menu:
    menu-5024: Menu
  widget:
    position-widget-6415: Search
  social:
    social-1026: Social
  copyright:
    copyright-1180: Copyright
  mobile-menu:
    mobile-menu-8149: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    feature: feature
    showcase: showcase
    utility: utility
    sidebar: sidebar
    mainbar: mainbar
    aside: aside
    expanded: expanded
    extension: extension
    bottom: bottom
    copyright: copyright
    offcanvas: offcanvas
    system-messages-9742: system-messages-9828
    logo-5274: logo-9680
    menu-5024: menu-5875
    position-widget-6415: position-widget-6279
    social-1026: social-3695
    copyright-1180: copyright-6444
    mobile-menu-8149: mobile-menu-2576
