name: she_farm
timestamp: 1678990742
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  infolist:
    infolist-2061: 'Info List'
  heading:
    heading-4091: Heading
  simplecontent:
    simplecontent-1800: 'Simple Content'
  logo:
    logo-1285: 'Logo / Image'
    logo-2625: 'Logo / Image'
  spacer:
    spacer-1640: Spacer
    spacer-5494: Spacer
  widget:
    position-widget-5778: Widget
    position-widget-1938: Search
  messages:
    system-messages-6685: 'System Messages'
  menu:
    menu-5087: Menu
  social:
    social-5556: Social
  copyright:
    copyright-6185: Copyright
  mobile-menu:
    mobile-menu-9364: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    showcase: showcase
    utility: utility
    sidebar: sidebar
    mainbar: mainbar
    aside: aside
    expanded: expanded
    extension: extension
    bottom: bottom
    copyright: copyright
    offcanvas: offcanvas
    system-messages-6685: system-messages-9828
    logo-2625: logo-9680
    menu-5087: menu-5875
    position-widget-1938: position-widget-6279
    social-5556: social-3695
    copyright-6185: copyright-6444
    mobile-menu-9364: mobile-menu-2576
