name: join_us
timestamp: 1603223577
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1581187522
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-4066: 'Page Content'
  messages:
    system-messages-8251: 'System Messages'
  logo:
    logo-5373: 'Logo / Image'
  menu:
    menu-1498: Menu
  widget:
    position-widget-8410: Search
  social:
    social-9153: Social
  blockcontent:
    blockcontent-3745: 'Block Content'
  copyright:
    copyright-4106: Copyright
  mobile-menu:
    mobile-menu-4546: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    slideshow: slideshow
    header: header
    above: above
    feature: feature
    showcase: showcase
    utility: utility
    sidebar: sidebar
    aside: aside
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-8251: system-messages-9828
    logo-5373: logo-9680
    menu-1498: menu-5875
    position-widget-8410: position-widget-6279
    social-9153: social-3695
    blockcontent-3745: blockcontent-5767
    copyright-4106: copyright-6444
    mobile-menu-4546: mobile-menu-2576
