name: hometown
timestamp: 1589245780
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1584382114
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-4720: 'Custom HTML'
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  messages:
    system-messages-9696: 'System Messages'
  logo:
    logo-5008: 'Logo / Image'
    logo-9614: 'Logo / Image'
  menu:
    menu-3188: Menu
  social:
    social-7870: Social
  copyright:
    copyright-9525: Copyright
  horizontalmenu:
    horizontalmenu-5586: 'Horizontal Menu'
  totop:
    totop-1604: 'To Top'
  mobile-menu:
    mobile-menu-7345: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-9696: system-messages-7972
    logo-5008: logo-9608
    menu-3188: menu-6409
    social-7870: social-3171
    logo-9614: logo-9571
    copyright-9525: copyright-1736
    horizontalmenu-5586: horizontalmenu-9034
    totop-1604: totop-8670
    mobile-menu-7345: mobile-menu-5697
